import { useConvexAuth } from "@convex-dev/auth/react";
import { Link } from "react-router-dom";
import { motion, useScroll, useTransform } from "framer-motion";
import {
  ArrowRight,
  CalendarClock,
  Clapperboard,
  CloudUpload,
  Cpu,
  Instagram,
  Play,
  Send,
  Sparkles,
  Youtube,
} from "lucide-react";
import { useRef } from "react";

import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  show: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.08, duration: 0.5, ease: "easeOut" as const },
  }),
};

export function LandingPage() {
  const { isAuthenticated } = useConvexAuth();
  const heroRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: heroRef,
    offset: ["start start", "end start"],
  });
  const bgY = useTransform(scrollYProgress, [0, 1], [0, 200]);

  const ctaHref = isAuthenticated ? "/dashboard" : "/auth?returnTo=/dashboard";

  return (
    <div className="min-h-screen overflow-x-hidden">
      {/* ---------- NAV ---------- */}
      <header className="fixed inset-x-0 top-0 z-50 border-b border-border/50 bg-background/70 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6">
          <Link to="/" className="flex items-center gap-2">
            <span className="rec-dot" />
            <span className="font-display text-lg font-bold tracking-wide">
              FACELESS <span className="text-primary">REELS</span>
            </span>
          </Link>
          <nav className="hidden items-center gap-8 text-sm text-muted-foreground md:flex">
            <a href="#how" className="transition-colors hover:text-foreground">How it works</a>
            <a href="#pipeline" className="transition-colors hover:text-foreground">The pipeline</a>
            <a href="#features" className="transition-colors hover:text-foreground">Features</a>
          </nav>
          <div className="flex items-center gap-3">
            {isAuthenticated ? (
              <Link to="/dashboard">
                <Button size="sm">Open studio</Button>
              </Link>
            ) : (
              <>
                <Link to="/auth" className="hidden sm:block">
                  <Button variant="ghost" size="sm">Sign in</Button>
                </Link>
                <Link to="/auth?returnTo=/dashboard">
                  <Button size="sm">Get started</Button>
                </Link>
              </>
            )}
          </div>
        </div>
      </header>

      {/* ---------- HERO ---------- */}
      <section ref={heroRef} className="relative pt-32 pb-24 sm:pt-40 sm:pb-32">
        <motion.div
          style={{ y: bgY }}
          className="pointer-events-none absolute inset-0 -z-10"
        >
          <div className="absolute left-1/2 top-0 h-[30rem] w-[60rem] -translate-x-1/2 rounded-full bg-primary/10 blur-[140px]" />
          <div className="absolute right-0 top-1/3 h-80 w-80 rounded-full bg-secondary/10 blur-[120px]" />
          <div className="absolute left-0 top-2/3 h-80 w-80 rounded-full bg-accent/5 blur-[120px]" />
        </motion.div>

        <div className="mx-auto max-w-6xl px-4 text-center sm:px-6">
          <motion.div variants={fadeUp} initial="hidden" animate="show" custom={0}>
            <Badge variant="outline" className="mb-6 px-4 py-1.5 font-mono text-xs tracking-wider">
              <span className="rec-dot mr-2" />
              AI VIDEO STUDIO · FULLY AUTOMATIC
            </Badge>
          </motion.div>

          <motion.h1
            variants={fadeUp}
            initial="hidden"
            animate="show"
            custom={1}
            className="mx-auto max-w-4xl font-display text-5xl font-bold leading-[1.05] tracking-tight sm:text-7xl"
          >
            Describe a video.
            <br />
            <span className="text-gradient">Your channel posts it.</span>
          </motion.h1>

          <motion.p
            variants={fadeUp}
            initial="hidden"
            animate="show"
            custom={2}
            className="mx-auto mt-6 max-w-2xl text-base leading-relaxed text-muted-foreground sm:text-lg"
          >
            Faceless Reels turns a one-line idea into a finished AI video — generated by
            Google Veo, titled, described, and published to your YouTube channel on
            autopilot. You write the queue once; the studio keeps posting.
          </motion.p>

          <motion.div
            variants={fadeUp}
            initial="hidden"
            animate="show"
            custom={3}
            className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row"
          >
            <Link to={ctaHref}>
              <Button size="lg" className="w-full sm:w-auto">
                <Play className="h-4 w-4" />
                Start your studio
              </Button>
            </Link>
            <a href="#how">
              <Button size="lg" variant="outline" className="w-full sm:w-auto">
                See how it works
                <ArrowRight className="h-4 w-4" />
              </Button>
            </a>
          </motion.div>

          {/* Hero console mock */}
          <motion.div
            variants={fadeUp}
            initial="hidden"
            animate="show"
            custom={4}
            className="mx-auto mt-16 max-w-3xl"
          >
            <div className="glass rounded-2xl p-1 shadow-2xl shadow-black/50">
              <div className="flex items-center gap-2 border-b border-border/60 px-4 py-3">
                <span className="h-3 w-3 rounded-full bg-destructive/70" />
                <span className="h-3 w-3 rounded-full bg-accent/60" />
                <span className="h-3 w-3 rounded-full bg-emerald-500/60" />
                <span className="ml-3 flex items-center gap-2 font-mono text-xs text-muted-foreground">
                  <Youtube className="h-3.5 w-3.5 text-secondary" />
                  studio · auto-pipeline
                </span>
                <span className="ml-auto flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
                  <span className="rec-dot" /> REC
                </span>
              </div>
              <div className="space-y-3 p-5 text-left font-mono text-sm">
                <div className="flex items-start gap-3">
                  <Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                  <p className="text-muted-foreground">
                    <span className="text-foreground">idea</span> = "Cinematic drone shot of a
                    neon Tokyo street at midnight, rain reflections"
                  </p>
                </div>
                <div className="flex items-start gap-3">
                  <Cpu className="mt-0.5 h-4 w-4 shrink-0 text-accent" />
                  <p>
                    <span className="text-emerald-400">veo</span> → generating…
                    <span className="ml-2 inline-block h-3 w-24 align-middle shimmer-bar rounded-sm" />
                  </p>
                </div>
                <div className="flex items-start gap-3">
                  <CloudUpload className="mt-0.5 h-4 w-4 shrink-0 text-secondary" />
                  <p>
                    <span className="text-foreground">youtube</span> → uploading
                    <span className="ml-2 text-muted-foreground">· privacy: public</span>
                  </p>
                </div>
                <div className="flex items-start gap-3">
                  <CalendarClock className="mt-0.5 h-4 w-4 shrink-0 text-foreground" />
                  <p className="text-foreground">
                    posted → <span className="text-primary">watch?v=…</span>
                    <span className="ml-2 text-muted-foreground">· next in 4h</span>
                  </p>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ---------- HOW IT WORKS ---------- */}
      <section id="how" className="relative py-24">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="mb-14 text-center">
            <Badge variant="secondary" className="mb-4 font-mono text-xs tracking-wider">
              HOW IT WORKS
            </Badge>
            <h2 className="font-display text-3xl font-bold sm:text-5xl">
              From idea to uploaded reel
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-muted-foreground">
              Three steps. Zero cameras. Zero editing. Zero hands after setup.
            </p>
          </div>

          <div className="grid gap-6 md:grid-cols-3">
            {[
              {
                icon: Send,
                step: "01",
                title: "Describe the idea",
                body: "Drop a prompt into your queue — “mountain sunrise timelapse” or “isometric city build”. Veo 3.1 turns it into real footage.",
                accent: "text-primary",
              },
              {
                icon: Cpu,
                step: "02",
                title: "AI generates it",
                body: "Google Veo renders the video in your chosen aspect ratio and duration while the studio watches the job for you.",
                accent: "text-accent",
              },
              {
                icon: Youtube,
                step: "03",
                title: "It posts itself",
                body: "The reel is titled, described, and uploaded to your YouTube channel — on a schedule you control, fully hands-free.",
                accent: "text-secondary",
              },
            ].map((f, i) => (
              <motion.div
                key={f.step}
                variants={fadeUp}
                initial="hidden"
                whileInView="show"
                viewport={{ once: true, margin: "-80px" }}
                custom={i}
                className="group relative overflow-hidden rounded-2xl border border-border/70 bg-card p-7 transition-all hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl hover:shadow-primary/10"
              >
                <span className="absolute -right-2 -top-4 font-display text-7xl font-bold text-muted/20 transition-colors group-hover:text-primary/15">
                  {f.step}
                </span>
                <f.icon className={`mb-5 h-8 w-8 ${f.accent}`} />
                <h3 className="mb-2 font-display text-lg font-semibold">{f.title}</h3>
                <p className="text-sm leading-relaxed text-muted-foreground">{f.body}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ---------- PIPELINE ---------- */}
      <section id="pipeline" className="relative py-24">
        <div className="pointer-events-none absolute inset-0 -z-10">
          <div className="absolute left-0 top-1/2 h-72 w-72 -translate-y-1/2 rounded-full bg-primary/5 blur-[100px]" />
          <div className="absolute right-0 top-1/4 h-72 w-72 rounded-full bg-secondary/5 blur-[100px]" />
        </div>
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="grid items-center gap-12 lg:grid-cols-2">
            <div>
              <Badge variant="accent" className="mb-4 font-mono text-xs tracking-wider">
                THE AUTOPILOT
              </Badge>
              <h2 className="font-display text-3xl font-bold leading-tight sm:text-4xl">
                A content engine that runs itself
              </h2>
              <p className="mt-4 leading-relaxed text-muted-foreground">
                Build a queue of ideas, connect your YouTube channel once, and pick how
                often it posts. Faceless Reels works the queue in order, waits out
                YouTube's quiet hours, and re-queues anything that fails.
              </p>
              <ul className="mt-8 space-y-4">
                {[
                  "Works down your idea queue in order — nothing posts twice",
                  "Schedule-based publishing with privacy controls (public / unlisted / private)",
                  "Automatic titles & descriptions from your templates",
                  "Retries failed generations so your channel never goes silent",
                ].map((item, i) => (
                  <motion.li
                    key={item}
                    variants={fadeUp}
                    initial="hidden"
                    whileInView="show"
                    viewport={{ once: true }}
                    custom={i}
                    className="flex items-start gap-3 text-sm text-muted-foreground"
                  >
                    <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-primary/15">
                      <span className="h-1.5 w-1.5 rounded-full bg-primary" />
                    </span>
                    {item}
                  </motion.li>
                ))}
              </ul>
              <Link to={ctaHref} className="mt-9 inline-block">
                <Button size="lg">
                  Turn it on
                  <ArrowRight className="h-4 w-4" />
                </Button>
              </Link>
            </div>

            <div className="relative">
              <div className="glass rounded-2xl p-6">
                <div className="mb-5 flex items-center justify-between">
                  <span className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
                    Pipeline status
                  </span>
                  <Badge variant="success" className="font-mono">
                    ● live
                  </Badge>
                </div>
                {[
                  { label: "Queue", value: "12 ideas", pct: 60, color: "bg-primary" },
                  { label: "Rendering", value: "veo-3.1", pct: 45, color: "bg-accent" },
                  { label: "Uploaded today", value: "8 / 12", pct: 66, color: "bg-secondary" },
                  { label: "Posted to YouTube", value: "8 reels", pct: 100, color: "bg-emerald-500" },
                ].map((row, i) => (
                  <motion.div
                    key={row.label}
                    variants={fadeUp}
                    initial="hidden"
                    whileInView="show"
                    viewport={{ once: true }}
                    custom={i}
                    className="mb-5 last:mb-0"
                  >
                    <div className="mb-1.5 flex items-center justify-between text-sm">
                      <span className="text-muted-foreground">{row.label}</span>
                      <span className="font-mono text-xs">{row.value}</span>
                    </div>
                    <div className="h-1.5 overflow-hidden rounded-full bg-muted">
                      <motion.div
                        initial={{ width: 0 }}
                        whileInView={{ width: `${row.pct}%` }}
                        viewport={{ once: true }}
                        transition={{ duration: 1, delay: 0.2 + i * 0.15, ease: "easeOut" }}
                        className={`h-full rounded-full ${row.color}`}
                      />
                    </div>
                  </motion.div>
                ))}
              </div>
              <div className="absolute -bottom-6 -right-4 hidden rotate-3 rounded-xl border border-secondary/40 bg-secondary/10 px-4 py-3 backdrop-blur sm:block">
                <div className="flex items-center gap-2 font-mono text-xs">
                  <Instagram className="h-4 w-4 text-secondary" />
                  <span>Reels-ready · 9:16</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ---------- FEATURES ---------- */}
      <section id="features" className="py-24">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="mb-14 text-center">
            <Badge variant="outline" className="mb-4 font-mono text-xs tracking-wider">
              FEATURES
            </Badge>
            <h2 className="font-display text-3xl font-bold sm:text-5xl">
              Everything a faceless channel needs
            </h2>
          </div>
          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            {[
              {
                icon: Sparkles,
                title: "Google Veo 3.1 powered",
                body: "State-of-the-art text-to-video from the Gemini API. 9:16, 16:9, or 1:1 — up to 8 seconds per clip.",
              },
              {
                icon: Youtube,
                title: "YouTube autopublish",
                body: "Connect your channel with one OAuth click. Refresh tokens keep posting alive for months.",
              },
              {
                icon: CalendarClock,
                title: "True scheduling",
                body: "Post every 2 hours, daily, or weekly. The pipeline respects the interval and never double-posts.",
              },
              {
                icon: Clapperboard,
                title: "Idea queue",
                body: "Stock the queue with as many prompts as you want. The studio works through them one by one.",
              },
              {
                icon: Send,
                title: "Template titles",
                body: "Drop {title} and {prompt} into your title & description templates for consistent SEO.",
              },
              {
                icon: CloudUpload,
                title: "Retries & recovery",
                body: "Failed generations are re-queued automatically and surfaced in your library for one-click retry.",
              },
            ].map((f, i) => (
              <motion.div
                key={f.title}
                variants={fadeUp}
                initial="hidden"
                whileInView="show"
                viewport={{ once: true, margin: "-60px" }}
                custom={i}
                className="rounded-2xl border border-border/70 bg-card/60 p-6 transition-all hover:border-primary/40 hover:bg-card"
              >
                <f.icon className="mb-4 h-6 w-6 text-primary" />
                <h3 className="mb-2 font-display text-base font-semibold">{f.title}</h3>
                <p className="text-sm leading-relaxed text-muted-foreground">{f.body}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ---------- CTA ---------- */}
      <section className="relative pb-28 pt-8">
        <div className="mx-auto max-w-4xl px-4 sm:px-6">
          <div className="glass relative overflow-hidden rounded-3xl px-6 py-16 text-center sm:px-16">
            <div className="pointer-events-none absolute inset-0 -z-0">
              <div className="absolute left-1/2 top-0 h-40 w-[30rem] -translate-x-1/2 rounded-full bg-primary/15 blur-[90px]" />
            </div>
            <div className="relative">
              <span className="rec-dot mb-6 inline-block" />
              <h2 className="font-display text-3xl font-bold sm:text-5xl">
                Your channel, on autopilot.
              </h2>
              <p className="mx-auto mt-4 max-w-lg text-muted-foreground">
                Connect YouTube, write your first idea, and let the studio start posting.
                Cancel anytime — your channel stays yours.
              </p>
              <div className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row">
                <Link to={ctaHref}>
                  <Button size="lg" className="w-full sm:w-auto">
                    Start your studio
                    <ArrowRight className="h-4 w-4" />
                  </Button>
                </Link>
              </div>
              <p className="mt-6 font-mono text-xs text-muted-foreground">
                60-second setup · no credit card
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ---------- FOOTER ---------- */}
      <footer className="border-t border-border/50 py-10">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 px-4 sm:flex-row sm:px-6">
          <div className="flex items-center gap-2">
            <span className="rec-dot" />
            <span className="font-display text-sm font-bold tracking-wide">
              FACELESS <span className="text-primary">REELS</span>
            </span>
          </div>
          <p className="text-xs text-muted-foreground">
            © {new Date().getFullYear()} Faceless Reels · AI video, fully automatic
          </p>
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            <Link to="/auth" className="hover:text-foreground">Sign in</Link>
            <a href="#how" className="hover:text-foreground">How it works</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
